[package]
name = "wave_rush"
version = "0.1.0"
authors = ["OhhhZenix <33815423+OhhhZenix@users.noreply.github.com>"]
edition = "2018"
build = "scripts/build.rs"

[build-dependencies]
fs_extra = "1.2.0"

[dependencies]
macroquad = "0.3.7"
specs = "0.17.0"