[package]
name = "wave_rush"
version = "0.1.0"
authors = ["OhhhZenix <33815423+OhhhZenix@users.noreply.github.com>"]
edition = "2018"
build = "scripts/build.rs"

[build-dependencies]
fs_extra = "1.2.0"
gl_generator = "0.14.0"

[dependencies]
image = "0.23.14"
cgmath = "0.18.0"
env_logger = "0.8.3"
log = "0.4.14"
glutin = "0.26.0"