# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Projects\WaveRush

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Projects\WaveRush

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Projects\WaveRush\CMakeFiles E:\Projects\WaveRush\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Projects\WaveRush\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WaveRush

# Build rule for target.
WaveRush: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 WaveRush
.PHONY : WaveRush

# fast build rule for target.
WaveRush/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/build
.PHONY : WaveRush/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f deps\SFML\src\SFML\System\CMakeFiles\sfml-system.dir\build.make deps/SFML/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-main

# Build rule for target.
sfml-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sfml-main
.PHONY : sfml-main

# fast build rule for target.
sfml-main/fast:
	$(MAKE) $(MAKESILENT) -f deps\SFML\src\SFML\Main\CMakeFiles\sfml-main.dir\build.make deps/SFML/src/SFML/Main/CMakeFiles/sfml-main.dir/build
.PHONY : sfml-main/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f deps\SFML\src\SFML\Window\CMakeFiles\sfml-window.dir\build.make deps/SFML/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f deps\SFML\src\SFML\Network\CMakeFiles\sfml-network.dir\build.make deps/SFML/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f deps\SFML\src\SFML\Graphics\CMakeFiles\sfml-graphics.dir\build.make deps/SFML/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) $(MAKESILENT) -f deps\SFML\src\SFML\Audio\CMakeFiles\sfml-audio.dir\build.make deps/SFML/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

src/Main.obj: src/Main.cpp.obj

.PHONY : src/Main.obj

# target to build an object file
src/Main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/Main.cpp.obj
.PHONY : src/Main.cpp.obj

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Utils.obj: src/Utils.cpp.obj

.PHONY : src/Utils.obj

# target to build an object file
src/Utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/Utils.cpp.obj
.PHONY : src/Utils.cpp.obj

src/Utils.i: src/Utils.cpp.i

.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s

.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/core/Game.obj: src/core/Game.cpp.obj

.PHONY : src/core/Game.obj

# target to build an object file
src/core/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/core/Game.cpp.obj
.PHONY : src/core/Game.cpp.obj

src/core/Game.i: src/core/Game.cpp.i

.PHONY : src/core/Game.i

# target to preprocess a source file
src/core/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/core/Game.cpp.i
.PHONY : src/core/Game.cpp.i

src/core/Game.s: src/core/Game.cpp.s

.PHONY : src/core/Game.s

# target to generate assembly for a file
src/core/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/core/Game.cpp.s
.PHONY : src/core/Game.cpp.s

src/entities/BasicEnemy.obj: src/entities/BasicEnemy.cpp.obj

.PHONY : src/entities/BasicEnemy.obj

# target to build an object file
src/entities/BasicEnemy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/BasicEnemy.cpp.obj
.PHONY : src/entities/BasicEnemy.cpp.obj

src/entities/BasicEnemy.i: src/entities/BasicEnemy.cpp.i

.PHONY : src/entities/BasicEnemy.i

# target to preprocess a source file
src/entities/BasicEnemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/BasicEnemy.cpp.i
.PHONY : src/entities/BasicEnemy.cpp.i

src/entities/BasicEnemy.s: src/entities/BasicEnemy.cpp.s

.PHONY : src/entities/BasicEnemy.s

# target to generate assembly for a file
src/entities/BasicEnemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/BasicEnemy.cpp.s
.PHONY : src/entities/BasicEnemy.cpp.s

src/entities/Entity.obj: src/entities/Entity.cpp.obj

.PHONY : src/entities/Entity.obj

# target to build an object file
src/entities/Entity.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/Entity.cpp.obj
.PHONY : src/entities/Entity.cpp.obj

src/entities/Entity.i: src/entities/Entity.cpp.i

.PHONY : src/entities/Entity.i

# target to preprocess a source file
src/entities/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/Entity.cpp.i
.PHONY : src/entities/Entity.cpp.i

src/entities/Entity.s: src/entities/Entity.cpp.s

.PHONY : src/entities/Entity.s

# target to generate assembly for a file
src/entities/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/Entity.cpp.s
.PHONY : src/entities/Entity.cpp.s

src/entities/EntityManager.obj: src/entities/EntityManager.cpp.obj

.PHONY : src/entities/EntityManager.obj

# target to build an object file
src/entities/EntityManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/EntityManager.cpp.obj
.PHONY : src/entities/EntityManager.cpp.obj

src/entities/EntityManager.i: src/entities/EntityManager.cpp.i

.PHONY : src/entities/EntityManager.i

# target to preprocess a source file
src/entities/EntityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/EntityManager.cpp.i
.PHONY : src/entities/EntityManager.cpp.i

src/entities/EntityManager.s: src/entities/EntityManager.cpp.s

.PHONY : src/entities/EntityManager.s

# target to generate assembly for a file
src/entities/EntityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/EntityManager.cpp.s
.PHONY : src/entities/EntityManager.cpp.s

src/entities/Player.obj: src/entities/Player.cpp.obj

.PHONY : src/entities/Player.obj

# target to build an object file
src/entities/Player.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/Player.cpp.obj
.PHONY : src/entities/Player.cpp.obj

src/entities/Player.i: src/entities/Player.cpp.i

.PHONY : src/entities/Player.i

# target to preprocess a source file
src/entities/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/Player.cpp.i
.PHONY : src/entities/Player.cpp.i

src/entities/Player.s: src/entities/Player.cpp.s

.PHONY : src/entities/Player.s

# target to generate assembly for a file
src/entities/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/Player.cpp.s
.PHONY : src/entities/Player.cpp.s

src/entities/SmartEnemy.obj: src/entities/SmartEnemy.cpp.obj

.PHONY : src/entities/SmartEnemy.obj

# target to build an object file
src/entities/SmartEnemy.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/SmartEnemy.cpp.obj
.PHONY : src/entities/SmartEnemy.cpp.obj

src/entities/SmartEnemy.i: src/entities/SmartEnemy.cpp.i

.PHONY : src/entities/SmartEnemy.i

# target to preprocess a source file
src/entities/SmartEnemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/SmartEnemy.cpp.i
.PHONY : src/entities/SmartEnemy.cpp.i

src/entities/SmartEnemy.s: src/entities/SmartEnemy.cpp.s

.PHONY : src/entities/SmartEnemy.s

# target to generate assembly for a file
src/entities/SmartEnemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\WaveRush.dir\build.make CMakeFiles/WaveRush.dir/src/entities/SmartEnemy.cpp.s
.PHONY : src/entities/SmartEnemy.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... WaveRush
	@echo ... sfml-audio
	@echo ... sfml-graphics
	@echo ... sfml-main
	@echo ... sfml-network
	@echo ... sfml-system
	@echo ... sfml-window
	@echo ... src/Main.obj
	@echo ... src/Main.i
	@echo ... src/Main.s
	@echo ... src/Utils.obj
	@echo ... src/Utils.i
	@echo ... src/Utils.s
	@echo ... src/core/Game.obj
	@echo ... src/core/Game.i
	@echo ... src/core/Game.s
	@echo ... src/entities/BasicEnemy.obj
	@echo ... src/entities/BasicEnemy.i
	@echo ... src/entities/BasicEnemy.s
	@echo ... src/entities/Entity.obj
	@echo ... src/entities/Entity.i
	@echo ... src/entities/Entity.s
	@echo ... src/entities/EntityManager.obj
	@echo ... src/entities/EntityManager.i
	@echo ... src/entities/EntityManager.s
	@echo ... src/entities/Player.obj
	@echo ... src/entities/Player.i
	@echo ... src/entities/Player.s
	@echo ... src/entities/SmartEnemy.obj
	@echo ... src/entities/SmartEnemy.i
	@echo ... src/entities/SmartEnemy.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

