name: Build

on:
  push:

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.build-type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake 4.3
        uses: ssrobins/install-cmake@v1
        with:
          version: 4.3.0

      - name: Show CMake version
        run: cmake --version

      - name: Configure
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: >
          cmake --build build
          --config ${{ matrix.build-type }}